### ISSUE TITLE
Error: Failed to send request

### ISSUE THREAD

**Issue by Aktr0s** [lovebrew/lovebrew-webserver#15]
When trying to build my test game in the bundler it throws error "Failed to send request", In browser console it gives an timeout.
Worth to note. 
When i refresh the page right after the error message, it gives 502 Bad Gateway and site won't load at all. After waiting a second or two start to load again.
Im also sending you a zip file of my game.

OS: Windows 10 64x
Browser: Brave (Chromium) v1.67.123
Version: Newest?
Im not using any proxy or vpn

PS. Please don't judge the game or/and code :)
[test_game.zip](https://github.com/user-attachments/files/16193511/test_game.zip)

**Comment by TurtleP** [comment]
Just to make sure, how long does it take before saying that it throws the timeout? @Nawias and I feel like we know what the fix is, but we want to be sure we're on the right track.

**Comment by Aktr0s** [comment]
About a minute.

**Comment by Aktr0s** [comment]
![image](https://github.com/user-attachments/assets/9ed6d7a8-2817-4d9f-857b-c76dea7194bf)

**Comment by TurtleP** [comment]
Okay, we've come up with some fixes to the beta site that will help. I tested your game against it, and it is working as expected. You can test it there and let me know how it is. It will take ~50 seconds for the bundle to process (if it hasn't cached everything).

**Comment by Aktr0s** [comment]
I tested it. It works! Thank you for help!
